<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Company>Mike Alimov</Company>
    <Product>Kadr</Product>
    <Authors>Mike Alimov</Authors>
    <Copyright>Copyright (c) 2026 Mike Alimov. PolyForm Noncommercial 1.0.0.</Copyright>
    <PackageLicenseExpression>PolyForm-Noncommercial-1.0.0</PackageLicenseExpression>
    <NeutralLanguage>ru-RU</NeutralLanguage>
    <SatelliteResourceLanguages>ru;en</SatelliteResourceLanguages>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
